apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kafka.fullname" . }}-certificate
  namespace: {{ .Release.Namespace }}
  labels:
   {{- include "kafka.labels" . | nindent 4 }}
type: Opaque
data:
  "kafka.key": |-
    {{ .Files.Get "config/kafka.key" | b64enc }}
  "kafka.crt": |-
    {{ .Files.Get "config/kafka.crt" | b64enc }}

